theme: jekyll-theme-hacker
title: 'deedoubledub'
description: 'technology, linux, gaming, hiking, fireworks'
show_downloads: false
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', '_posts/template.md']
